require: rubocop-rails
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'define', 'it']
  Exclude:
    - 'config/environments/*.rb'
    - 'spec/factories/*.rb'

Metrics/MethodLength:
  Max: 20
  ExcludedMethods: ['change']
Metrics/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
Documentation:
  Enabled: false