require: rubocop-rails

AllCops:
  NewCops: enable

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'define', 'it', 'let']
  Exclude:
    - 'config/environments/*.rb'
    - 'spec/factories/*.rb'

Metrics/MethodLength:
  Max: 20
  IgnoredMethods: ['change']

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
Documentation:
  Enabled: false