version: '2'
services:
  db:
    image: postgres:12.1
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=superpassword
      - POSTGRES_USER=automation
      - POSTGRES_DB=automation_development
    ports:
      - "3317:5432"
    networks:
      net1:
        aliases:
          - db
  web:
    image: 252636471646.dkr.ecr.us-east-2.amazonaws.com/automation-web:latest
    networks:
      net1:
        aliases:
          - web
    ports:
      - 3001:3001
    mem_reservation: 256m
  api:
    image: 252636471646.dkr.ecr.us-east-2.amazonaws.com/automation:latest
    mem_reservation: 256m
    networks:
      net1:
        aliases:
          - api
    depends_on:
      - influx
    links:
      - influx:influx
      - redis:redis
      - db:db
    volumes:
      - ./:/app
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=superpassword
      - POSTGRES_USER=automation
      - INFLUX_HOST=influx
      - POSTGRES_HOST=db
      - POSTGRES_PORT=3317
      - REDIS_PASSWORD=superpassword
      - REDIS_HOST=redis
      - RAILS_ENV=development
      - BUNDLER_WITHOUT=production
    ports:
      - 3000:3000
    command: bundle exec rails s

  influx:
    image: 252636471646.dkr.ecr.us-east-2.amazonaws.com/automation-influx:latest
    mem_reservation: 256m
    volumes:
      - ./tmp/influx:/var/lib/influxdb
    networks:
      net1:
        aliases:
          - influx
  redis:
    image: 252636471646.dkr.ecr.us-east-2.amazonaws.com/automation-redis:latest
    mem_reservation: 256m
    environment:
      - REDIS_PASSWORD=superpassword
    volumes:
      - ./tmp/redis:/bitnami/redis/data
    networks:
      net1:
        aliases:
          - redis

  nginx:
    image: 252636471646.dkr.ecr.us-east-2.amazonaws.com/automation-proxy:latest
    mem_reservation: 16m
    networks:
      net1:
        aliases:
          - nginx
    ports:
      - 80:80
      - 443:443
    links:
      - api
      - web

networks:
  net1:
