version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.14.0
  aws-cli: circleci/aws-cli@1.3.0

executors:
  default:
    working_directory: ~/automation
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
          BUNDLER_VERSION: 2.0.1
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          PG_HOST: 127.0.0.1
          PGUSER: pi
          RUBYOPT: '-W:no-deprecated'
      - image: circleci/postgres:12.0
        environment:
          POSTGRES_DB: automation_test
          POSTGRES_USER: pi
      - image: influxdb:1.8.0
        environment:
          INFLUXDB_DB: automation


commands:
  configure_bundler:
    description: Configure bundler
    steps:
      - run:
          name: Configure bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - automation-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - automation-
      - configure_bundler
      - run:
          name: Install bundle
          command: bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
      - run:
          name: Setup DB
          command: bundle exec rails db:schema:load --trace
      - run:
          name: RSpec
          command: bundle exec rspec --profile 10 --format progress
      - save_cache:
          key: automation-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: ~/
          paths:
            - ./automation
  rubocop:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - configure_bundler
      - run:
          name: Rubocop
          command: bundle exec rubocop
  restart_task:
    executor: aws-cli/default
    steps:
      - aws-cli/install
      - run:
          name: Restart task
          command: |
            aws ecs update-service --cluster automation-cluster --service automation-service --force-new-deployment

workflows:
  version: 2
  integration:
    jobs:
        - build
        - rubocop:
            requires:
              - build
  build-image:
    jobs:
        - aws-ecr/build-and-push-image:
            repo: "${AWS_RESOURCE_NAME_PREFIX}"
            tag: "latest"
        - restart_task:
            requires:
              - aws-ecr/build-and-push-image
